/**
 * Tests for the v0.2 engine upgrades: learned quality (inference half),
 * durable state, wire payloads, and the HTTP decide-sidecar. The expected
 * numbers here are GENERATED BY THE PYTHON ENGINE — if they drift, the two
 * runtimes disagree and parity is broken.
 */
import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync, writeFileSync, unlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  Message,
  RoutingRequest,
  WorkloadClass,
  PolicyEngine,
  PriceRegistry,
  BackendRegistry,
  BackendSpec,
  DeploymentClass,
  WorkloadResolver,
  QualityModel,
  extractFeatures,
  FEATURE_NAMES,
  N_FEATURES,
  restoreSnapshot,
  createDecideServer,
  saveSnapshotFile,
  loadSnapshotFile,
} from "../dist/index.js";

const CK_WEIGHTS = [
  0.02, -0.01, 0.05, 0.0, -0.08, 0.03, 0.04, 0.01, 0.0, -0.02,
  0.03, 0.07, -0.05, 0.01, 0.02, -0.03, 0.06,
];
const CHECKPOINT = {
  format: "llmrouter-quality-v1",
  shrinkage_k: 20,
  feature_names: [...FEATURE_NAMES],
  heads: {
    "claude-haiku-class": { bias: 0.05, weights: CK_WEIGHTS, samples: 40 },
    "gpt-mini-class": {
      bias: -0.10, weights: CK_WEIGHTS.map((w) => -w), samples: 8,
    },
  },
};

function makeEngine(qualityModel = null) {
  const prices = new PriceRegistry();
  const ids = prices.ids();
  const backends = new BackendRegistry([
    new BackendSpec("anthropic", {
      deployment: DeploymentClass.Api,
      models: ids.filter((m) => m.startsWith("claude")), priority: 0,
    }),
    new BackendSpec("openai", {
      deployment: DeploymentClass.Api,
      models: ids.filter((m) => m.startsWith("gpt")), priority: 1,
    }),
  ]);
  return new PolicyEngine(
    prices, backends, new WorkloadResolver(), undefined, null, qualityModel,
  );
}

// --------------------------------------------------------------------------- //
// learned quality — inference half
// --------------------------------------------------------------------------- //
test("feature vector matches the Python anchor (code request)", () => {
  const req = new RoutingRequest(
    [new Message("user", "def f(): ``` import os ``` refactor this")],
  );
  const x = extractFeatures(req, WorkloadClass.Code);
  assert.equal(x.length, N_FEATURES);
  assert.deepEqual([...x].map((v) => Number(v.toFixed(12))), [
    0, 0, 0, 0, 1, 0,           // one-hot: code
    0, 0, 0,                    // tools / tool_results / images
    0, 0,                       // n_tools / tool_schema_size
    0,                          // prefix_size
    0.04, 1, 0.5,               // turn_depth, is_first_turn, code_markers
    0,                          // retrieved_count
    0.40319596418,              // user_text_size
  ].map((v) => Number(v.toFixed(12))));
});

test("QualityModel.fromJson validates the checkpoint envelope", () => {
  const qm = QualityModel.fromJson(structuredClone(CHECKPOINT));
  assert.equal(qm.heads.size, 2);
  assert.throws(() => QualityModel.fromJson({ format: "other" }), /format/);
  const bad = structuredClone(CHECKPOINT);
  bad.feature_names[0] = "nope";
  assert.throws(() => QualityModel.fromJson(bad), /feature set/);
});

test("learned-quality decision matches the Python figure exactly", () => {
  const qm = QualityModel.fromJson(structuredClone(CHECKPOINT));
  const engine = makeEngine(qm);
  const req = new RoutingRequest(
    [new Message("user", "x".repeat(4000))], WorkloadClass.Chat,
  );
  const d = engine.decide(req);
  assert.equal(d.modelId, "claude-haiku-class"); // the head flipped this one
  const top = d.candidates[0];
  assert.ok(Math.abs(top.quality - 0.818021685514) < 1e-11, String(top.quality));
  assert.ok(
    d.reasons.some((r) => r.startsWith("learned-quality: 2/6")),
    d.reasons.join(" | "),
  );
  // and without the checkpoint the prior path answers
  const plain = makeEngine().decide(req);
  assert.notEqual(plain.modelId, "claude-haiku-class");
});

// --------------------------------------------------------------------------- //
// durable state
// --------------------------------------------------------------------------- //
test("restores a PYTHON-generated snapshot (cross-runtime state)", () => {
  const pySnapshot = {
    format: "llmrouter-state-v1",
    version: 1,
    saved_wall: 1790305773.4896972,
    sessions: {
      "sid:xr": {
        workload: "agent", source: "structural", confidence: 0.9,
        pinned_model: "claude-sonnet-class", pinned_backend: "anthropic",
        pinned_at_age: 100.0, switched_at_age: null, expires_in: -3599.99,
        turns_seen: 0, prefix_tokens: 0,
        observed_cache_hit_rate: 0.888888888888889,
        ewma_hits: 0.26666666666666666, ewma_total: 0.3,
        stranded_count: 2, invalidators_hash: "abababababababab",
        last_seen_age: 0.00003,
      },
    },
    backend_health: {
      anthropic: {
        successes: 0, failures: 1, consecutive_failures: 1,
        ewma_latency_ms: 0, p99_latency_ms: 0, open_until_age: 0,
        rate_limited_until_age: 0, last_error: "boom",
      },
    },
    fingerprints: {
      map: { "fp-x": { workload: "chat", source: "structural",
                       confidence: 0.8, reason: "py-seeded" } },
      seen_by_client: {},
    },
    // python-only sections: TS must tolerate them untouched
    pairs: {}, counters: {},
  };
  const engine = makeEngine();
  restoreSnapshot(engine, pySnapshot);
  const s = engine.sessions.peek("sid:xr");
  assert.ok(s);
  assert.equal(s.pinnedModel, "claude-sonnet-class");
  assert.equal(s.strandedCount, 2);
  assert.ok(Math.abs(s.observedCacheHitRate - 8 / 9) < 1e-12);
  assert.ok(engine.resolver.fingerprints.get("fp-x"));
  assert.equal(engine.backends.health("anthropic").consecutiveFailures, 1);
});

test("TS snapshot roundtrips through the file store", (t) => {
  const path = join(tmpdir(), `llmrouter-state-${process.pid}-${Date.now()}.json`);
  const engine = makeEngine();
  const req = new RoutingRequest(
    [new Message("user", "hello there friend")], WorkloadClass.Chat, "roundtrip",
  );
  const d = engine.decide(req);
  engine.recordDecision(req, d, { cacheReadTokens: 900, cacheWriteTokens: 100 });
  saveSnapshotFile(path, engine);

  const engine2 = makeEngine();
  assert.equal(loadSnapshotFile(path, engine2), true);
  const s = engine2.sessions.peek("sid:roundtrip");
  assert.ok(s);
  assert.equal(s.pinnedModel, d.modelId);
  assert.ok(Math.abs(s.observedCacheHitRate - 0.9) < 1e-12);
  unlinkSync(path);
  assert.equal(loadSnapshotFile(path, makeEngine()), false); // first boot
});

// --------------------------------------------------------------------------- //
// wire payloads
// --------------------------------------------------------------------------- //
test("RoutingRequest.fromPayload covers the Python surface", () => {
  const req = RoutingRequest.fromPayload({
    messages: [{ role: "system", content: "s" }, { role: "user", content: "hi" }],
    workload: "rag",
    retrieved: ["a chunk"],
    tools: [{ name: "t" }],
    tags: ["code"],
    constraints: { max_cost_usd: 0.01, allowed_models: ["gpt-mini-class"],
                   residency_tags: ["eu"] },
    expected_turns: 3,
    session_id: "wire",
  });
  assert.equal(req.workload, WorkloadClass.Rag);
  assert.equal(req.retrieved.length, 1);
  assert.equal(req.constraints.maxCostUsd, 0.01);
  assert.equal(req.stickyKey(), "sid:wire");
  assert.throws(() => RoutingRequest.fromPayload({}), /messages/);
  assert.throws(
    () => RoutingRequest.fromPayload({ messages: [{ content: "x" }],
                                       workload: "nonsense" }),
    /unknown workload/,
  );
});

test("Decision.toPayload carries the same fields as the Python side", () => {
  const engine = makeEngine();
  const req = new RoutingRequest(
    [new Message("user", "def f(): ``` import x ``` code code")],
  );
  const p = engine.decide(req).toPayload();
  for (const key of ["model_id", "backend_id", "workload", "ttl_by_segment",
    "candidates", "reasons", "sticky_key", "workload_source"]) {
    assert.ok(key in p, key);
  }
  assert.equal(p.workload, "code");
  assert.ok(p.candidates.length > 1);
  assert.ok("score" in p.candidates[0] && "switch_cost_usd" in p.candidates[0]);
});

// --------------------------------------------------------------------------- //
// HTTP decide-sidecar
// --------------------------------------------------------------------------- //
async function withServer(options, fn) {
  const sc = createDecideServer(options);
  await new Promise((resolve) => sc.server.listen(0, "127.0.0.1", resolve));
  const base = `http://127.0.0.1:${sc.server.address().port}`;
  try {
    await fn(base, sc);
  } finally {
    await new Promise((resolve) => sc.server.close(resolve));
  }
}

test("sidecar: healthz, decide, 400 and 404", async () => {
  await withServer({}, async (base) => {
    const h = await fetch(`${base}/healthz`);
    assert.deepEqual(await h.json(), { ok: true, engine: "llmrouter" });

    const d = await fetch(`${base}/decide`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        messages: [{ role: "user", content: "def f(): ``` import bug ``` code code" }],
        session_id: "http1",
      }),
    });
    assert.equal(d.status, 200);
    const payload = await d.json();
    assert.equal(payload.workload, "code");
    assert.ok(payload.candidates.length >= 2);

    const bad = await fetch(`${base}/decide`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: "{not json",
    });
    assert.equal(bad.status, 400);
    assert.equal((await fetch(`${base}/nope`)).status, 404);
  });
});

test("sidecar: bearer token gate", async () => {
  await withServer({ token: "pw" }, async (base) => {
    assert.equal((await fetch(`${base}/healthz`)).status, 401);
    const ok = await fetch(`${base}/healthz`,
      { headers: { authorization: "Bearer pw" } });
    assert.equal(ok.status, 200);
  });
});

test("sidecar: observed_usage feeds affinity and state persists", async () => {
  const path = join(tmpdir(), `llmrouter-sidecar-${process.pid}.json`);
  const long = "hello friend ".repeat(300);
  await withServer({ statePath: path }, async (base, sc) => {
    const body1 = { messages: [{ role: "user", content: long }],
                    session_id: "aff" };
    await fetch(`${base}/decide`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(body1),
    });
    const d2 = await (await fetch(`${base}/decide`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        messages: [{ role: "user", content: long },
                   { role: "assistant", content: "ok" },
                   { role: "user", content: "more " + long }],
        session_id: "aff",
        observed_usage: { cache_read_tokens: 5000, cache_write_tokens: 100 },
      }),
    })).json();
    assert.equal(d2.reused_session, true);
    const warm = d2.candidates.find((c) => c.model_id === d2.model_id);
    assert.ok(warm.reasons.includes("warm=true"), JSON.stringify(warm.reasons));
    assert.ok(Math.abs(
      sc.engine.sessions.peek("sid:aff").observedCacheHitRate - 50 / 51,
    ) < 1e-9);
  });
  // the snapshot survived the server; a fresh engine can load it
  const revived = makeEngine();
  assert.equal(loadSnapshotFile(path, revived), true);
  assert.ok(revived.sessions.peek("sid:aff"));
  unlinkSync(path);
});
