"""Learned quality heads: the offline-trained layer under the quality term.

The price-card `quality_prior` is a hand-set placeholder. This module replaces
the guess with a measurement, following the RouteLLM pattern — train offline on
preference data, ship a frozen JSON checkpoint, infer in milliseconds — with
two differences that matter:

  * **Zero dependencies.** A quality head is 17 weights and a bias; SGD on a
    logistic loss is 40 lines of stdlib. No torch, no sklearn, no model server.
  * **Shrinkage, not replacement.** The learned delta is blended with the prior
    via λ = n/(n+k): with no data you get exactly the old behaviour; the model
    only talks as loudly as its sample count earns.

    quality(m, x) = clamp( prior(m, workload) + λ · (b + w·x), 0, 1 )

Feature extraction is pure and deterministic; the JS engine ports it
byte-for-byte (same JSON.stringify/serialization order, same float64 dot
product) so both runtimes make identical decisions from the same checkpoint.
Training lives HERE only — checkpoints are portable artifacts, and the JS side
consumes them without needing a trainer.

Feedback data format (JSONL, one sample per line):

    pointwise: {"text": "...", "model": "gpt-mini-class", "outcome": 1}
              "outcome" ∈ {0,1} bool/0/1/"good"/"bad", or a judge score in
              [0,1]. Optional: "messages", "workload".
    pairwise:  {"text": "...", "model_a": "x", "model_b": "y",
                "winner": "a"|"b"|"tie"}
              expands into two pointwise samples (tie → 0.5/0.5).
    generated by: Router.report_feedback(...) + Router.export_feedback()
"""
from __future__ import annotations

import json
import math
import random
import sys
from dataclasses import dataclass
from typing import Any, Mapping, Sequence

from .pricing import PriceCard
from .signals import _CODE_MARKERS
from .types import Message, RoutingRequest, WorkloadClass

CHECKPOINT_FORMAT = "llmrouter-quality-v1"

#: FIXED ORDER. The JS engine mirrors this list exactly; changing it invalidates
#: every checkpoint (the checkpoint's own feature_names field is checked on load).
FEATURE_NAMES: tuple[str, ...] = (
    "wl_agent", "wl_chat", "wl_rag", "wl_batch", "wl_code", "wl_vision",
    "has_tools", "has_tool_results", "has_images",
    "n_tools", "tool_schema_size", "prefix_size",
    "turn_depth", "is_first_turn", "code_markers",
    "retrieved_count", "user_text_size",
)
N_FEATURES = len(FEATURE_NAMES)

_WORKLOAD_ONEHOT = (
    WorkloadClass.AGENT, WorkloadClass.CHAT, WorkloadClass.RAG,
    WorkloadClass.BATCH, WorkloadClass.CODE, WorkloadClass.VISION,
)


def _log_norm(chars: float, divisor: float) -> float:
    """Squash a character count into [0, 1] on a log scale."""
    return min(1.0, math.log10(1.0 + chars) / divisor)


def _tool_chars(tool: Mapping[str, Any]) -> int:
    # Same serialization as policy._tool_chars: insertion order, compact
    # separators, byte-comparable with JSON.stringify in the JS engine.
    return len(json.dumps(tool, separators=(",", ":")))


def extract_features(req: RoutingRequest,
                     workload: WorkloadClass) -> tuple[float, ...]:
    """Deterministic feature vector for one request. Pure, no clock, no I/O."""
    onehot = [1.0 if workload is w else 0.0 for w in _WORKLOAD_ONEHOT]

    tool_chars = sum(_tool_chars(t) for t in req.tools)
    prefix_chars = 0
    for m in req.messages:
        if m.role == "system":
            prefix_chars += len(m.text)
        elif m.role != "user" or not req.is_first_turn:
            prefix_chars += len(m.text)
    prefix_chars += sum(len(r) for r in req.retrieved)

    user_text = req.first_user_text()
    code_hits = sum(1 for marker in _CODE_MARKERS if marker in user_text)

    return tuple(onehot) + (
        1.0 if req.tools else 0.0,
        1.0 if req.has_tool_results() else 0.0,
        1.0 if req.has_images() else 0.0,
        min(1.0, len(req.tools) / 8.0),
        _log_norm(tool_chars, 5.0),
        _log_norm(prefix_chars + tool_chars, 5.0),
        min(1.0, req.turn_index / 25.0),
        1.0 if req.is_first_turn else 0.0,
        min(1.0, code_hits / 6.0),
        min(1.0, len(req.retrieved) / 4.0),
        _log_norm(len(user_text), 4.0),
    )


# --------------------------------------------------------------------------- #
# The checkpoint
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class ModelHead:
    bias: float
    weights: tuple[float, ...]
    samples: int

    def raw(self, x: Sequence[float]) -> float:
        """b + w·x, summed in feature order (both runtimes, same float64)."""
        acc = self.bias
        for w, xi in zip(self.weights, x):
            acc += w * xi
        return acc


class QualityModel:
    """Frozen heads loaded from a checkpoint; the prior is the fallback."""

    def __init__(self, heads: Mapping[str, ModelHead],
                 shrinkage_k: float = 20.0,
                 feature_names: tuple[str, ...] = FEATURE_NAMES) -> None:
        if tuple(feature_names) != FEATURE_NAMES:
            raise ValueError(
                "checkpoint feature set does not match this engine version — "
                "retrain it with `llmrouter train`"
            )
        self.heads = dict(heads)
        self.shrinkage_k = shrinkage_k
        self.feature_names = tuple(feature_names)

    # ---- inference ------------------------------------------------------ #
    def quality(self, card: PriceCard, workload: WorkloadClass,
                x: Sequence[float]) -> float:
        base = card.quality(workload.value)
        head = self.heads.get(card.model_id)
        if head is None or base < 0:
            return base
        lam = head.samples / (head.samples + self.shrinkage_k)
        return min(1.0, max(0.0, base + lam * head.raw(x)))

    def coverage(self, model_ids: Sequence[str]) -> tuple[int, int]:
        """(models with heads, models in the pool) — for explainability."""
        return sum(1 for m in model_ids if m in self.heads), len(model_ids)

    # ---- serialization --------------------------------------------------- #
    def to_dict(self) -> dict[str, Any]:
        return {
            "format": CHECKPOINT_FORMAT,
            "shrinkage_k": self.shrinkage_k,
            "feature_names": list(self.feature_names),
            "heads": {
                mid: {"bias": h.bias, "weights": list(h.weights),
                      "samples": h.samples}
                for mid, h in sorted(self.heads.items())
            },
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent, sort_keys=True)

    def save(self, path: str) -> None:
        with open(path, "w", encoding="utf-8") as f:
            f.write(self.to_json())

    @classmethod
    def from_dict(cls, obj: Mapping[str, Any]) -> "QualityModel":
        fmt = obj.get("format")
        if fmt != CHECKPOINT_FORMAT:
            raise ValueError(
                f"unsupported checkpoint format {fmt!r}, "
                f"expected {CHECKPOINT_FORMAT!r}"
            )
        heads = {
            mid: ModelHead(
                bias=float(h["bias"]),
                weights=tuple(float(w) for w in h["weights"]),
                samples=int(h["samples"]),
            )
            for mid, h in (obj.get("heads") or {}).items()
        }
        for mid, h in heads.items():
            if len(h.weights) != N_FEATURES:
                raise ValueError(
                    f"head {mid!r} has {len(h.weights)} weights, "
                    f"expected {N_FEATURES}"
                )
        return cls(heads, shrinkage_k=float(obj.get("shrinkage_k", 20.0)),
                   feature_names=tuple(obj.get("feature_names") or ()))

    @classmethod
    def loads(cls, text: str) -> "QualityModel":
        return cls.from_dict(json.loads(text))

    @classmethod
    def load(cls, path: str) -> "QualityModel":
        with open(path, encoding="utf-8") as f:
            return cls.loads(f.read())


# --------------------------------------------------------------------------- #
# Feedback samples
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class FeedbackSample:
    features: tuple[float, ...]
    model_id: str
    outcome: float  # 0..1; 0.5 = tie / uncertain


def _outcome(value: Any) -> float:
    if isinstance(value, bool):
        return 1.0 if value else 0.0
    if isinstance(value, (int, float)):
        return min(1.0, max(0.0, float(value)))
    text = str(value).lower()
    if text in ("good", "ok", "win", "correct", "1", "true"):
        return 1.0
    if text in ("bad", "fail", "loss", "wrong", "misrouted", "0", "false"):
        return 0.0
    if text in ("tie", "equal"):
        return 0.5
    raise ValueError(f"unrecognised outcome {value!r}")


def parse_feedback_line(obj: Mapping[str, Any]) -> list[FeedbackSample]:
    """One JSONL line -> zero or more samples. Pairwise rows expand to two."""
    messages = obj.get("messages")
    if messages:
        msgs = tuple(
            Message(str(m.get("role", "user")), str(m.get("content", "")))
            for m in messages
        )
    else:
        text = obj.get("text", obj.get("prompt"))
        if text is None:
            raise ValueError("feedback row needs 'text' or 'messages'")
        msgs = (Message("user", str(text)),)

    workload_raw = obj.get("workload")
    workload = (WorkloadClass(str(workload_raw)) if workload_raw
                else WorkloadClass.CHAT)
    req = RoutingRequest(messages=msgs, workload=workload)
    x = extract_features(req, workload)

    if "winner" in obj:
        a, b = obj.get("model_a"), obj.get("model_b")
        if not a or not b:
            raise ValueError("pairwise rows need model_a and model_b")
        w = str(obj["winner"]).lower()
        y = 1.0 if w in ("a", "model_a") else 0.0 if w in ("b", "model_b") else 0.5
        return [FeedbackSample(x, str(a), y), FeedbackSample(x, str(b), 1.0 - y)]

    model = obj.get("model")
    if not model:
        raise ValueError("feedback row needs 'model' or (model_a/model_b/winner)")
    return [FeedbackSample(x, str(model), _outcome(obj.get("outcome", 1)))]


def load_feedback(path: str) -> list[FeedbackSample]:
    if path == "-":
        raw = sys.stdin.read()
    else:
        with open(path, encoding="utf-8") as f:
            raw = f.read()
    samples: list[FeedbackSample] = []
    for lineno, line in enumerate(raw.splitlines(), start=1):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        obj = json.loads(line)
        try:
            samples.extend(parse_feedback_line(obj))
        except (ValueError, KeyError) as exc:
            raise ValueError(f"line {lineno}: {exc}") from exc
    return samples


# --------------------------------------------------------------------------- #
# Training: per-model logistic head, plain SGD, no dependencies
# --------------------------------------------------------------------------- #
def _sigmoid(z: float) -> float:
    if z >= 0:
        return 1.0 / (1.0 + math.exp(-z))
    e = math.exp(z)
    return e / (1.0 + e)


@dataclass(frozen=True)
class HeadReport:
    model_id: str
    samples: int
    mean_outcome: float
    train_accuracy: float
    eval_accuracy: float | None


def train_heads(samples: Sequence[FeedbackSample], *, epochs: int = 200,
                lr: float = 0.25, l2: float = 1e-4, holdout: float = 0.2,
                min_samples: int = 8, seed: int = 13,
                shrinkage_k: float = 20.0,
                ) -> tuple[QualityModel, list[HeadReport]]:
    """Fit one logistic head per model. Models below `min_samples` keep the
    prior untouched — this is why the blend is safe on thin data."""
    by_model: dict[str, list[FeedbackSample]] = {}
    for s in samples:
        by_model.setdefault(s.model_id, []).append(s)

    rng = random.Random(seed)
    heads: dict[str, ModelHead] = {}
    reports: list[HeadReport] = []

    for model_id in sorted(by_model):
        rows = by_model[model_id]
        if len(rows) < min_samples:
            continue
        idx = list(range(len(rows)))
        rng.shuffle(idx)
        n_eval = int(len(rows) * holdout)
        eval_rows = [rows[i] for i in idx[:n_eval]]
        train_rows = [rows[i] for i in idx[n_eval:]]
        if not train_rows:
            continue

        w = [0.0] * N_FEATURES
        b = 0.0
        for _ in range(epochs):
            order = list(range(len(train_rows)))
            rng.shuffle(order)
            for i in order:
                row = train_rows[i]
                z = b
                for j, xj in enumerate(row.features):
                    z += w[j] * xj
                err = _sigmoid(z) - row.outcome
                b -= lr * err
                for j, xj in enumerate(row.features):
                    w[j] -= lr * (err * xj + l2 * w[j])

        def accuracy(rows: Sequence[FeedbackSample]) -> float:
            hits = 0
            for r in rows:
                z = b + sum(wj * xj for wj, xj in zip(w, r.features))
                if (_sigmoid(z) >= 0.5) == (r.outcome >= 0.5):
                    hits += 1
            return hits / len(rows)

        mean_y = sum(r.outcome for r in rows) / len(rows)
        heads[model_id] = ModelHead(bias=b, weights=tuple(w), samples=len(rows))
        reports.append(HeadReport(
            model_id=model_id, samples=len(rows), mean_outcome=mean_y,
            train_accuracy=accuracy(train_rows),
            eval_accuracy=accuracy(eval_rows) if eval_rows else None,
        ))

    return QualityModel(heads, shrinkage_k=shrinkage_k), reports


__all__ = [
    "CHECKPOINT_FORMAT",
    "FEATURE_NAMES",
    "N_FEATURES",
    "extract_features",
    "ModelHead",
    "QualityModel",
    "FeedbackSample",
    "parse_feedback_line",
    "load_feedback",
    "HeadReport",
    "train_heads",
]
